### PR TITLE
Include Souffle headers + fix writeAll API

### PR DESCRIPTION
**Pull request by csabahruska**
I've added Souffle headers so that it gets installed along with souffle-haskell and the headers will be in path when the embedded C++ files are compiled.
I also added directory path parameter to writeAll (printAll) function.
Made a comment in the package.yaml why it uses the cpp-options instead cxx-options.
Added cxx-options to be future proof.

### CODE REVIEW

**Comment by luc-tielen** [comment]
Hi, thanks for these improvements!
Maybe it's best to split these into 2 PRs though (if it's not too much trouble)? One for the printAll/writeFiles fixes, another for header files?

Also, regarding the header files. Do they not get installed somewhere in the PATH if you install souffle normally via package manager / manual build? (I guess I am spoiled by Nix which does this automatically). If not, maybe we should consider adding souffle as a git submodule, so the libraries are always in sync (now we run the risk of lagging behind on the souffle version), and I think it's less maintenance too.

**Comment by csabahruska** [comment]
Sure, I can split the PR.
Of course Souffle installs its headers, but that is for the developer users that write and compile datalog.
The headers in souffle-haskell are for users that want to use a package that contains an analysis generated by souffle. Why would they install Souffle then?

**Comment by csabahruska** [comment]
Either souffle-haskell includes the headers that the generated C++ code depends on, or the users should include it in their package each time.

**Comment by luc-tielen** [comment]
Ah I get it now, thanks for pointing that out. But wouldn't the git submodule approach be better than copying the header files into the repo every now and then? Easier to maintain and then we can say: "This version of souffle haskell works with version X of souffle" (probably pointing to a release tag).

**Comment by csabahruska** [comment]
True, the submodule approach is nice and simple solution.

**Comment by csabahruska** [comment]
print all parameter addition:
https://github.com/luc-tielen/souffle-haskell/pull/14

I will not make PR for souffle header addition.

**Pull request closed without merging**
